project:
  type: website 
  resources:
    - resume.pdf

website:
  title: "Oliver Siu"
  navbar:
    right:
      
      - href: index.qmd
        text: Home
        
      - href: projects.qmd
        text: Projects
        
      - href: about.qmd
        text: About
        
  page-footer:
    right: "&copy; {{< now year >}} Oliver Siu"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

execute:
  freeze: auto
