---
title: "About Me"
---

## Background

I'm currently pursuing my Master's in Applied Data Science, at the University of Chicago, and I recently graduated from UCLA where I majored in Statistics and Data Science.

I'm experienced with Python, R, and SQL. My nontraditional path to higher education took me to many places across the globe including Hong Kong, Taiwan, and Tahiti, to name a few. Navigating different languages and cultures developed strong adaptability and pattern recognition skills that I bring to data analysis and problem-solving.

## Hobbies

  - Drawing
  - Photography
  - Music Composition
  - Musical Instruments:
    - Alto Saxophone
    - Tenor Saxophone
    - Flute
    - Piano
    - Electric Guitar

## Skills

  - **Coding Languages:** R, Python, SQL
  - **Technical Software:** Visual Studio Code, RStudio, JupyterLab, Microsoft Office
  - **Creative Software:** Tableau, Voyant Tools, Ableton Live, Sibelius, Finale, Adobe Creative Cloud (After Effects, Audition, Illustrator, Media Encoder, Photoshop, and Premiere Pro)
  - **Languages:**
    - Primary Language: English
    - Fluent in verbal Mandarin and Cantonese

## Let's Connect!

Feel free to reach out to me on [LinkedIn](https://www.linkedin.com/in/oliver-siu/) or check out my projects on [Github](https://github.com/oliverdsiu).

I look forward to discussing how I can contribute to your team!
